#include <iostream>
#include <vector>
#include <string>
#include <unordered_map>
#include <map>
#include <memory>
#include <sstream>
#include <fstream>
#include <cctype>
#include <algorithm>
#include <variant>
#include <cmath>
#include <stdexcept>
#include <limits>
#include <chrono>
#include <thread>
#include <ctime>
#include <filesystem>
#include <unordered_set>
#include <stack>
#include <functional>
#include <cmath>

#include "SetColor.h"